# Generated by Django 5.0 on 2023-12-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Netrokona', 'Netrokona'), ('Kishoreganj', 'Kishoreganj'), ('Pirojpur', 'Pirojpur'), ('Jhalokathi', 'Jhalokathi'), ('Bhola', 'Bhola'), ('Barguna', 'Barguna'), ('Patuakhali', 'Patuakhali'), ('Barishal', 'Barishal'), ('Lakshmipur', 'Lakshmipur'), ('Chandpur', 'Chandpur'), ('Noakhali', 'Noakhali'), ('Feni', 'Feni'), ('Comilla', 'Comilla'), ('Brahmanbaria', 'Brahmanbaria'), ('Narsingdi', 'Narsingdi'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Tangail', 'Tangail'), ('Munshiganj', 'Munshiganj'), ('Manikganj', 'Manikganj'), ('Rajbari', 'Rajbari'), ('Kishoreganj', 'Kishoreganj'), ('Gopalganj', 'Gopalganj'), ('Madaripur', 'Madaripur'), ('Shariatpur', 'Shariatpur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Mymensingh', 'Mymensingh'), ('Netrokona', 'Netrokona'), ('Kurigram', 'Kurigram'), ('Lalmonirhat', 'Lalmonirhat'), ('Rangpur', 'Rangpur'), ('Gaibandha', 'Gaibandha'), ('Nilphamari', 'Nilphamari'), ('Dinajpur', 'Dinajpur'), ('Thakurgaon', 'Thakurgaon'), ('Panchagarh', 'Panchagarh'), ('Bogra', 'Bogra'), ('Joypurhat', 'Joypurhat'), ('Naogaon', 'Naogaon'), ('Natore', 'Natore'), ('Chapainawabganj', 'Chapainawabganj'), ('Kushtia', 'Kushtia'), ('Jhenaidah', 'Jhenaidah'), ('Magura', 'Magura'), ('Meherpur', 'Meherpur'), ('Narail', 'Narail'), ('Khulna', 'Khulna'), ('Satkhira', 'Satkhira'), ('Bagerhat', 'Bagerhat'), ('Chuadanga', 'Chuadanga'), ('Jashore', 'Jashore'), ('Jhalokathi', 'Jhalokathi'), ('Sarishabari', 'Sarishabari'), ('Fulbari', 'Fulbari'), ('Rajshahi', 'Rajshahi'), ('Pabna', 'Pabna'), ('Bogra', 'Bogra'), ('Joypurhat', 'Joypurhat'), ('Naogaon', 'Naogaon'), ('Natore', 'Natore'), ('Chapainawabganj', 'Chapainawabganj')], max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
            ],
        ),
    ]
